version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  metrics-exposer:
    image: metricsexposer
    container_name: metricsexposer
    ports:
      - "8080:8080"
  metrics-exposer-fallback:
    image: metricsexposer
    container_name: metricsexposerfallback
    ports:
      - "8081:8080"