services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # extra_hosts injects a dns to the /etc/hosts file, so that these services will have a resolvable IP address
    extra_hosts:
      - 'host.docker.internal:host-gateway'
# OR
#      - 'host.docker.internal:172.17.0.1'

  metrics-exposer:
    image: metricsexposer
    container_name: metricsexposer
    ports:
      - "8080:8080"

  metrics-exposer-fallback:
    image: metricsexposer
    container_name: metricsexposerfallback
    ports:
      - "8081:8080"