  scrape_configs:
      - job_name: 'backend'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 3s
        static_configs:
          - targets: []
            labels:
              application: 'app'
